chore: depcheck dependency version

diff --git a/.github/workflows/snapshot-docker.yml b/.github/workflows/snapshot-docker.yml
--- a/.github/workflows/snapshot-docker.yml
+++ b/.github/workflows/snapshot-docker.yml
@@ -24,14 +24,13 @@ jobs:
           mkdir -p ~/.m2
           echo '<settings><servers><server><id>github</id><username></username><password>${{ secrets.GITHUB_TOKEN }}</password></server></servers></settings>' > ~/.m2/settings.xml
 
-      - name: Copy Maven settings into Docker context
-        run: cp ~/.m2/settings.xml ./settings.xml
-
-      - name: Verify settings.xml before Docker build
+      - name: Copy Maven settings into repository (to include in Docker build)
         run: |
-          echo "Checking if settings.xml exists..."
-          ls -l settings.xml || echo "settings.xml NOT found!"
-          cat settings.xml || echo "Unable to read settings.xml!"
+          cp ~/.m2/settings.xml $GITHUB_WORKSPACE/settings.xml
+          ls -l $GITHUB_WORKSPACE/settings.xml || echo "settings.xml NOT found in workspace!"
+
+      - name: Debug List all files in workspace before Docker build
+        run: ls -la
 
       - name: 📦 Docker build and push
         id: release
